"""Arithmetic dataset: data generation, prompt formatting, and output parsing.

The experiment replicates Section 5.2 / 7.1 of the project report:
  Prompt: "x = {x}, y = {y}. Calculate: 1. 3x, 2. 2y, 3. 3x + 2y"
  x, y ~ Uniform[1, 10^5)

Two prompt representations are maintained per sample:

  rollout_prompt   – full few-shot prompt fed to the base model (vllm).
  supervisor_state – compressed single-line state fed to the supervisor GPT-2,
                     following the "#|>" / "||" format from the paper (§C.2.1).
"""
from __future__ import annotations

import random
import re
from dataclasses import dataclass, field
from typing import Optional

from ig_tool_use.config import COT_SEP, SEP_TOKEN

# ---------------------------------------------------------------------------
# Few-shot prompt for the base model (matches Section C.2 of the paper).
# ---------------------------------------------------------------------------
_FEW_SHOT_PREFIX = """\
x = 23, y = 51. Please calculate the following:
1. 3x
2. 2y
3. 3x + 2y
Answer:
1. 3x = 69
2. 2y = 102
3. 3x + 2y = 171

x = 35, y = 60. Please calculate the following:
1. 3x
2. 2y
3. 3x + 2y
Answer:
1. 3x = 105
2. 2y = 120
3. 3x + 2y = 225

"""

# ---------------------------------------------------------------------------
# Data structure
# ---------------------------------------------------------------------------

@dataclass
class ArithmeticSample:
    x: int
    y: int
    # Ground-truth values
    step1_gt: int           # 3x
    step2_gt: int           # 2y
    step3_gt: int           # 3x + 2y (the correct final answer Y)

    # Model-generated values (filled by rollout)
    step1_model: Optional[int] = None
    step2_model: Optional[int] = None
    step3_model: Optional[int] = None

    # Raw text generated by the model
    model_raw: str = ""

    # Supervisor states  X_0^M … X_3^M  (paper §C.2.1 format)
    # These use the compressed single-line representation with "||" separators.
    sup_state_0: str = field(default="", repr=False)  # prompt only
    sup_state_1: str = field(default="", repr=False)  # + step 1
    sup_state_2: str = field(default="", repr=False)  # + step 1-2
    sup_state_3: str = field(default="", repr=False)  # + step 1-3

    # Target Y fed to the supervisor: always the CORRECT final answer.
    @property
    def supervisor_target(self) -> str:
        return f"3x + 2y = {self.step3_gt}"

    # Convenience accuracy flags
    @property
    def step1_correct(self) -> bool:
        return self.step1_model == self.step1_gt

    @property
    def step2_correct(self) -> bool:
        return self.step2_model == self.step2_gt

    @property
    def step3_correct(self) -> bool:
        return self.step3_model == self.step3_gt

    @property
    def final_correct(self) -> bool:
        return self.step3_model == self.step3_gt


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

def make_rollout_prompt(x: int, y: int) -> str:
    """Full few-shot prompt for vllm generation.  The model completes from 'Answer:\\n'."""
    return (
        _FEW_SHOT_PREFIX
        + f"x = {x}, y = {y}. Please calculate the following:\n"
        "1. 3x\n"
        "2. 2y\n"
        "3. 3x + 2y\n"
        "Answer:\n"
    )


def _supervisor_prompt_base(x: int, y: int) -> str:
    """Compressed single-line prompt used in supervisor states (no few-shot examples)."""
    return (
        f"x = {x}, y = {y}. Please calculate the following: "
        "1. 3x 2. 2y 3. 3x + 2y Answer:"
    )


def make_supervisor_state(
    x: int,
    y: int,
    step1_val: Optional[int] = None,
    step2_val: Optional[int] = None,
    step3_val: Optional[int] = None,
) -> str:
    """Build the supervisor state string for a given set of completed steps.

    Matches the format from paper §C.2.1:
      state_0: "x = {x}, ... Answer:"
      state_1: "x = {x}, ... Answer: || 1. 3x = {v1}"
      state_2: "x = {x}, ... Answer: || 1. 3x = {v1} || 2. 2y = {v2}"
      state_3: "x = {x}, ... Answer: || 1. 3x = {v1} || 2. 2y = {v2} || 3. 3x + 2y = {v3}"
    """
    state = _supervisor_prompt_base(x, y)
    if step1_val is not None:
        state += COT_SEP + f"1. 3x = {step1_val}"
    if step2_val is not None:
        state += COT_SEP + f"2. 2y = {step2_val}"
    if step3_val is not None:
        state += COT_SEP + f"3. 3x + 2y = {step3_val}"
    return state


def make_step_text(step: int, val: int) -> str:
    """Format a single step line for appending to the rollout prompt."""
    if step == 1:
        return f"1. 3x = {val}\n"
    elif step == 2:
        return f"2. 2y = {val}\n"
    else:
        return f"3. 3x + 2y = {val}\n"


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def _parse_int(text: str) -> Optional[int]:
    """Extract first integer (possibly float like '69.0') from a string."""
    m = re.search(r"[-+]?\d+(?:\.\d+)?", text)
    if m is None:
        return None
    try:
        return int(float(m.group()))
    except ValueError:
        return None


def parse_model_output(sample: ArithmeticSample, raw: str) -> ArithmeticSample:
    """Parse raw model output and populate step values and supervisor states."""
    sample.model_raw = raw

    # Step 1: "1. 3x = <val>"
    m1 = re.search(r"1\.\s*3x\s*=\s*([\d.]+)", raw)
    sample.step1_model = int(float(m1.group(1))) if m1 else None

    # Step 2: "2. 2y = <val>"
    m2 = re.search(r"2\.\s*2y\s*=\s*([\d.]+)", raw)
    sample.step2_model = int(float(m2.group(1))) if m2 else None

    # Step 3: "3. 3x + 2y = <val>" or "3. 3x+2y = <val>"
    m3 = re.search(r"3\.\s*3x\s*\+\s*2y\s*=\s*([\d.]+)", raw)
    sample.step3_model = int(float(m3.group(1))) if m3 else None

    # Build supervisor states using the MODEL's outputs.
    sample.sup_state_0 = make_supervisor_state(sample.x, sample.y)
    sample.sup_state_1 = make_supervisor_state(sample.x, sample.y, sample.step1_model)
    sample.sup_state_2 = make_supervisor_state(
        sample.x, sample.y, sample.step1_model, sample.step2_model
    )
    sample.sup_state_3 = make_supervisor_state(
        sample.x, sample.y, sample.step1_model, sample.step2_model, sample.step3_model
    )

    return sample


# ---------------------------------------------------------------------------
# Dataset generation
# ---------------------------------------------------------------------------

def generate_samples(n: int, seed: int = 42) -> list[ArithmeticSample]:
    """Generate n random arithmetic samples with ground-truth values."""
    rng = random.Random(seed)
    samples: list[ArithmeticSample] = []
    for _ in range(n):
        x = rng.randint(1, 10**5 - 1)
        y = rng.randint(1, 10**5 - 1)
        s = ArithmeticSample(
            x=x,
            y=y,
            step1_gt=3 * x,
            step2_gt=2 * y,
            step3_gt=3 * x + 2 * y,
        )
        s.sup_state_0 = make_supervisor_state(x, y)
        samples.append(s)
    return samples
